name: build and create release

on:
    push:

env:
    # tokens
    GH_TOKEN: ${{ secrets.PAT }}
    GITHUB_TOKEN: ${{ secrets.PAT }}

    # paths
    UE_PATH: "C:\\\"Program Files\"\\\"Unreal Engine - CSS\""
    SML_CACHE_PATH: "C:\\Users\\Administrator\\Documents\\SML"

    # or use a repo?
    MAIN_MOD: allFluidsAreGasses
    PLUGIN_NAMES: '"allFluidsAreGasses", "KPrivateCodeLib", "KUI", "KBFL"'
    PLUGIN_NAMES_PARAM: '"allFluidsAreGasses" "KPrivateCodeLib" "KUI" "KBFL"'

jobs:
    build-mod:
        name: Build Mod and Prepare Releases
        timeout-minutes: 180
        runs-on: self-hosted
        working-directory: "C:\\Users\\Administrator\\Documents\\workflow"
        steps:
            - name: Clone Patcher
              uses: actions/checkout@v3
              with:
                repository: Satisfactory-KMods/WorkflowPatcher
                path: Patcher
                token: ${{ secrets.PAT }}

            - name: Use SML Cache
              run: |
                $robocopy_process = Start-Process "robocopy" -ArgumentList "${{ env.SML_CACHE_PATH }} $PWD\SML /S /E /R:5 /W:5 /TBD /MT:12 /LOG:copy.log" -PassThru -Wait
                if ($robocopy_process.ExitCode -ne 1) { exit 1 }

            # uncomment this for Satisfactory Plus!
            - name: Clone Repos
              run: |
                Git-Clone "https://oauth2:${{ secrets.PAT }}@github.com/Satisfactory-KMods/allFluidsAreGasses.git" "$PWD/SML/Mods/allFluidsAreGasses"
                Git-Clone "https://oauth2:${{ secrets.PAT }}@github.com/Satisfactory-KMods/KPrivateCodeLib.git" "$PWD/SML/Mods/KPrivateCodeLib"
                Git-Clone "https://oauth2:${{ secrets.PAT }}@github.com/Satisfactory-KMods/KBFL.git" "$PWD/SML/Mods/KBFL"
                Git-Clone "https://oauth2:${{ secrets.PAT }}@github.com/Satisfactory-KMods/KUI.git" "$PWD/SML/Mods/KUI"

            - name: List Mods
              run: Get-ChildItem -Path "$PWD/SML/Mods" -Directory -Force -ErrorAction SilentlyContinue | Select-Object FullName
                
            - name: Run Patcher and Version Updater
              run: |
                cd Patcher
                pnpm i
                pnpm run Header
                pnpm run Content
                pnpm run UpdateUPlugins ${{ env.MAIN_MOD }}
                cd ..

            - name: Generate project
              run: |
                ${{ env.UE_PATH }}\Engine\Build\BatchFiles\Build.bat -projectfiles -project="$PWD\SML\FactoryGame.uproject" -game -rocket -progres

            - name: Build c++ dev editor
              run: |
                MSBuild.exe $PWD\SML\FactoryGame.sln /p:Configuration="Development Editor" /p:Platform="Win64" /t:"Games\FactoryGame"

            - name: Build c++ shipping
              run: |
                MSBuild.exe $PWD\SML\FactoryGame.sln /p:Configuration="Shipping" /p:Platform="Win64" /t:"Games\FactoryGame"

            - name: Package allFluidsAreGasses
              run: |
                $plugins = ${{ env.PLUGIN_NAMES }}
                $PLUGIN = $plugins[0]
              run: |
                MSBuild.exe $PWD\SML\FactoryGame.sln /p:Configuration="Shipping" /p:Platform="Win64" /t:"Games\FactoryGame"

            - name: Package KPrivateCodeLib
              run: |
                $plugins = ${{ env.PLUGIN_NAMES }}
                $PLUGIN = $plugins[1]
              run: |
                MSBuild.exe $PWD\SML\FactoryGame.sln /p:Configuration="Shipping" /p:Platform="Win64" /t:"Games\FactoryGame"

            - name: Package KUI
              run: |
                $plugins = ${{ env.PLUGIN_NAMES }}
                $PLUGIN = $plugins[2]
              run: |
                MSBuild.exe $PWD\SML\FactoryGame.sln /p:Configuration="Shipping" /p:Platform="Win64" /t:"Games\FactoryGame"

            - name: Package KBFL
              run: |
                $plugins = ${{ env.PLUGIN_NAMES }}
                $PLUGIN = $plugins[3]

            - name: Archive Artifact Result
              uses: actions/upload-artifact@v2
              with:
                name: "result.zip"
                retention-days: 30
                if-no-files-found: error
                path: "SML\\Saved\\ArchivedPlugins"

            - name: Create Cache
              run: | 
                Remove-Item "${{ env.SML_CACHE_PATH }}" -Recurse -Force
                $robocopy_process = Start-Process "robocopy" -ArgumentList "$PWD\SML ${{ env.SML_CACHE_PATH }} /S /E /R:5 /W:5 /TBD /MT:12 /LOG:copy.log" -PassThru -Wait
                if ($robocopy_process.ExitCode -ne 1) { exit 1 }
                Remove-Item "${{ env.SML_CACHE_PATH }}\Saved\ArchivedPlugins" -Recurse -Force

            - name: Package for Patreon
              run: |
                cd Patcher
                pnpm run PreparePatreon ${{ env.PLUGIN_NAMES_PARAM }}
                cd ..

            - name: Archive Artifact Compressed Patreon
              uses: actions/upload-artifact@v2
              with:
                name: "compressed.zip"
                retention-days: 30
                if-no-files-found: error
                path: "Zips"

            - name: Cleanup
              if: always()
              run: |
                $paths = (Get-ChildItem).FullName
                foreach($filePath in $paths)
                {
                  Remove-Item $filePath -Recurse -Force
                  Write-Host "Path $filePath removed"
                }
                Write-Host "Cleared"

    release-patreon:
        needs: build-mod
        if: github.ref == 'refs/heads/dev'
        name: Release Patreon Version
        timeout-minutes: 180
        runs-on: ubuntu-latest
        steps:
          - run: echo hello world!

    release-smr:
        needs: build-mod
        if: github.ref == 'refs/heads/main'
        name: Release SMR Version
        timeout-minutes: 180
        runs-on: ubuntu-latest
        steps:
          - run: echo hello world!